version: '3.8'

services:
  # ThingsBoard IoT Platform
  thingsboard:
    image: thingsboard/tb-postgres:latest
    ports:
      - "8080:9090"      # ThingsBoard Web UI
      - "1883:1883"      # MQTT
      - "7070:7070"      # RPC
      - "5683-5688:5683-5688/udp"  # CoAP
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # Configure for reverse proxy
      TB_SERVER_WS_URL: /api/ws
      TB_SERVER_HTTP_BIND_ADDRESS: 0.0.0.0
      TB_SERVER_HTTP_BIND_PORT: 9090
    depends_on:
      - postgres
    networks:
      - farm_network
    restart: unless-stopped

  # PostgreSQL Database for ThingsBoard
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - farm_network
    restart: unless-stopped

  # Farm Control Demo with Chainlit + GROQ + MCP
  farm-control-demo:
    build: .
    container_name: farm-control-demo
    expose:
      - "8000"     # Internal only - accessed via nginx
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_PROJECT_API_KEY=${OPENAI_PROJECT_API_KEY}
      - THINGSBOARD_HOST=thingsboard
      - THINGSBOARD_PORT=9090
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=thingsboard
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - farm-data:/app/data
      - ./logs:/app/logs
    networks:
      - farm_network
    depends_on:
      - thingsboard
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ThingsBoard with Copilot - Simple iframe + floating widget approach
  thingsboard-with-copilot:
    build: 
      context: ./src/thingsboard-with-copilot
      dockerfile: Dockerfile
    container_name: thingsboard-with-copilot
    expose:
      - "9000"     # Internal only - accessed via nginx
    environment:
      - THINGSBOARD_URL=http://localhost:8080
      - CHAINLIT_URL=/copilot  # Use relative path through nginx
      - PORT=9000
    networks:
      - farm_network
    depends_on:
      - thingsboard
      - farm-control-demo
    restart: unless-stopped

  # Nginx Gateway (ONLY exposed port)
  nginx:
    image: nginx:alpine
    container_name: farm-nginx
    ports:
      - "9001:9001"     # ONLY this port exposed
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - farm-control-demo
      - thingsboard-with-copilot
    networks:
      - farm_network
    restart: unless-stopped



volumes:
  logs:
  postgres-data:
  farm-data:

networks:
  farm_network:
    driver: bridge
